name: 功能建议
description: 提出新功能或改进建议
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的功能建议！请描述你的使用场景和期望的功能。

  - type: dropdown
    id: sdk
    attributes:
      label: 相关 SDK
      description: 该功能涉及哪个 SDK？
      multiple: true
      options:
        - 全部 SDK
        - Go
        - npm (TypeScript)
        - Rust
        - Python
        - C
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      description: 该建议属于哪个类别？
      options:
        - 新渠道支持
        - API 改进
        - 性能优化
        - 文档改进
        - 开发体验
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 你遇到了什么问题或不便？这个功能要解决什么痛点？
      placeholder: "目前使用 SDK 时需要手动处理..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 你期望的功能是怎样的？如果可能，请附上 API 设计示例
      placeholder: |
        希望能支持 xxx 功能，API 示例：
        ```typescript
        const result = await someNewFunction({ ... });
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你是否考虑过其他解决方案？
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 其他相关信息，如参考链接、截图等
    validations:
      required: false
