package com.xxxxteam.tempmail

import com.xxxxteam.tempmail.providers.*

/**
 * 全部 279 个渠道的注册入口（严格按 .baseline_channels.txt 顺序）。
 *
 * 由 [Registry] 首次访问时调用 [init] 完成注册，`TempMail.listChannels()`
 * 输出顺序与基线逐行一致。参数化渠道使用 (channel, domain) 或 (channel, baseUrl) 构造。
 */
object RegistryChannels {

    @Volatile
    private var done = false

    /** 注册全部渠道（幂等）。 */
    @Synchronized
    fun init() {
        if (done) return
        done = true
        Registry.register(ChannelSpec("tempmail", "TempMail", "tempmail.ing"), Tempmail)
        Registry.register(ChannelSpec("tempmail-cn", "TempMail CN", "tempmail.cn"), TempmailCn)
        Registry.register(ChannelSpec("ta-easy", "TA Easy", "ta-easy.com"), TaEasy)
        Registry.register(ChannelSpec("10minute-one", "10 Minute Email", "10minutemail.one"), TenminuteOne("10minute-one", "10minutemail.one"))
        Registry.register(ChannelSpec("xghff-com", "xghff.com", "10minutemail.one"), TenminuteOne("xghff-com", "xghff.com"))
        Registry.register(ChannelSpec("oqqaj-com", "oqqaj.com", "10minutemail.one"), TenminuteOne("oqqaj-com", "oqqaj.com"))
        Registry.register(ChannelSpec("psovv-com", "psovv.com", "10minutemail.one"), TenminuteOne("psovv-com", "psovv.com"))
        Registry.register(ChannelSpec("dbwot-com", "dbwot.com", "10minutemail.one"), TenminuteOne("dbwot-com", "dbwot.com"))
        Registry.register(ChannelSpec("ygwpr-com", "ygwpr.com", "10minutemail.one"), TenminuteOne("ygwpr-com", "ygwpr.com"))
        Registry.register(ChannelSpec("imxwe-com", "imxwe.com", "10minutemail.one"), TenminuteOne("imxwe-com", "imxwe.com"))
        Registry.register(ChannelSpec("linshiyou", "临时邮", "linshiyou.com"), Linshiyou)
        Registry.register(ChannelSpec("mffac", "MFFAC", "mffac.com"), Mffac)
        Registry.register(ChannelSpec("tempmail-lol", "TempMail LOL", "tempmail.lol"), TempMailLol)
        Registry.register(ChannelSpec("chatgpt-org-uk", "ChatGPT Mail", "mail.chatgpt.org.uk"), ChatgptOrgUk)
        Registry.register(ChannelSpec("temp-mail-io", "Temp-Mail.io", "temp-mail.io"), TempMailIo)
        Registry.register(ChannelSpec("mail-cx", "Mail.cx", "mail.cx"), MailCx("mail-cx", "mail.cx"))
        Registry.register(ChannelSpec("ddker-com", "ddker.com", "mail.cx"), MailCx("ddker-com", "ddker.com"))
        Registry.register(ChannelSpec("catchmail", "Catchmail", "catchmail.io"), Catchmail("catchmail", "catchmail.io"))
        Registry.register(ChannelSpec("catchmail-mailistry", "Catchmail Mailistry", "mailistry.com"), Catchmail("catchmail-mailistry", "mailistry.com"))
        Registry.register(ChannelSpec("catchmail-zeppost", "Catchmail Zeppost", "zeppost.com"), Catchmail("catchmail-zeppost", "zeppost.com"))
        Registry.register(ChannelSpec("mailforspam", "MailForSpam", "mailforspam.com"), MailForSpam("mailforspam", "mailforspam.com"))
        Registry.register(ChannelSpec("mailforspam-tempmail-io", "MailForSpam TempMail.io", "tempmail.io"), MailForSpam("mailforspam-tempmail-io", "tempmail.io"))
        Registry.register(ChannelSpec("mailforspam-disposable", "MailForSpam Disposable", "disposable.email"), MailForSpam("mailforspam-disposable", "disposable.email"))
        Registry.register(ChannelSpec("tempmailc", "TempMailC", "tempmailc.com"), Tempmailc)
        Registry.register(ChannelSpec("mailnesia", "Mailnesia", "mailnesia.com"), Mailnesia)
        Registry.register(ChannelSpec("throwawaymail", "ThrowawayMail", "throwawaymail.app"), ThrowawayMail)
        Registry.register(ChannelSpec("tempmail-fish", "TempMail Fish", "tempmail.fish"), TempMailFish)
        Registry.register(ChannelSpec("neighbours-sh", "Neighbours", "neighbours.sh"), NeighboursSh)
        Registry.register(ChannelSpec("shitty-email", "shitty.email", "shitty.email"), ShittyEmail)
        Registry.register(ChannelSpec("tempmailpro", "TempMail Pro", "tempmailpro.us"), TempMailPro)
        Registry.register(ChannelSpec("devmail-uk", "DevMail UK", "devmail.uk"), DevmailUk)
        Registry.register(ChannelSpec("inboxkitten", "InboxKitten", "inboxkitten.com"), InboxKitten)
        Registry.register(ChannelSpec("cleantempmail", "CleanTempMail", "cleantempmail.com"), CleanTempMail)
        Registry.register(ChannelSpec("getnada", "GetNada", "getnada.net"), Getnada("getnada", "getnada.net"))
        Registry.register(ChannelSpec("1vpn-net", "1vpn.net", "getnada.net"), Getnada("1vpn-net", "1vpn.net"))
        Registry.register(ChannelSpec("abematv-com", "abematv.com", "getnada.net"), Getnada("abematv-com", "abematv.com"))
        Registry.register(ChannelSpec("abematv-net", "abematv.net", "getnada.net"), Getnada("abematv-net", "abematv.net"))
        Registry.register(ChannelSpec("abematv-org", "abematv.org", "getnada.net"), Getnada("abematv-org", "abematv.org"))
        Registry.register(ChannelSpec("aceh-cc", "aceh.cc", "getnada.net"), Getnada("aceh-cc", "aceh.cc"))
        Registry.register(ChannelSpec("bangkabelitung-net", "bangkabelitung.net", "getnada.net"), Getnada("bangkabelitung-net", "bangkabelitung.net"))
        Registry.register(ChannelSpec("cctruyen-com", "cctruyen.com", "getnada.net"), Getnada("cctruyen-com", "cctruyen.com"))
        Registry.register(ChannelSpec("getnada-com", "getnada.com", "getnada.net"), Getnada("getnada-com", "getnada.com"))
        Registry.register(ChannelSpec("getnada-email", "getnada.email", "getnada.net"), Getnada("getnada-email", "getnada.email"))
        Registry.register(ChannelSpec("getnada-net", "getnada.net", "getnada.net"), Getnada("getnada-net", "getnada.net"))
        Registry.register(ChannelSpec("jawatengah-net", "jawatengah.net", "getnada.net"), Getnada("jawatengah-net", "jawatengah.net"))
        Registry.register(ChannelSpec("jawatimur-net", "jawatimur.net", "getnada.net"), Getnada("jawatimur-net", "jawatimur.net"))
        Registry.register(ChannelSpec("kalimantanbarat-net", "kalimantanbarat.net", "getnada.net"), Getnada("kalimantanbarat-net", "kalimantanbarat.net"))
        Registry.register(ChannelSpec("kalimantanselatan-net", "kalimantanselatan.net", "getnada.net"), Getnada("kalimantanselatan-net", "kalimantanselatan.net"))
        Registry.register(ChannelSpec("kalimantantengah-net", "kalimantantengah.net", "getnada.net"), Getnada("kalimantantengah-net", "kalimantantengah.net"))
        Registry.register(ChannelSpec("kalimantantimur-net", "kalimantantimur.net", "getnada.net"), Getnada("kalimantantimur-net", "kalimantantimur.net"))
        Registry.register(ChannelSpec("kalimantanutara-net", "kalimantanutara.net", "getnada.net"), Getnada("kalimantanutara-net", "kalimantanutara.net"))
        Registry.register(ChannelSpec("kepulauanriau-net", "kepulauanriau.net", "getnada.net"), Getnada("kepulauanriau-net", "kepulauanriau.net"))
        Registry.register(ChannelSpec("luxury345-com", "luxury345.com", "getnada.net"), Getnada("luxury345-com", "luxury345.com"))
        Registry.register(ChannelSpec("malukuutara-net", "malukuutara.net", "getnada.net"), Getnada("malukuutara-net", "malukuutara.net"))
        Registry.register(ChannelSpec("nusatenggarabarat-net", "nusatenggarabarat.net", "getnada.net"), Getnada("nusatenggarabarat-net", "nusatenggarabarat.net"))
        Registry.register(ChannelSpec("nusatenggaratimur-net", "nusatenggaratimur.net", "getnada.net"), Getnada("nusatenggaratimur-net", "nusatenggaratimur.net"))
        Registry.register(ChannelSpec("papuabarat-net", "papuabarat.net", "getnada.net"), Getnada("papuabarat-net", "papuabarat.net"))
        Registry.register(ChannelSpec("papuabaratdaya-net", "papuabaratdaya.net", "getnada.net"), Getnada("papuabaratdaya-net", "papuabaratdaya.net"))
        Registry.register(ChannelSpec("papuaselatan-net", "papuaselatan.net", "getnada.net"), Getnada("papuaselatan-net", "papuaselatan.net"))
        Registry.register(ChannelSpec("pehol-com", "pehol.com", "getnada.net"), Getnada("pehol-com", "pehol.com"))
        Registry.register(ChannelSpec("ptruyen-com", "ptruyen.com", "getnada.net"), Getnada("ptruyen-com", "ptruyen.com"))
        Registry.register(ChannelSpec("pulaubali-net", "pulaubali.net", "getnada.net"), Getnada("pulaubali-net", "pulaubali.net"))
        Registry.register(ChannelSpec("riau-net", "riau.net", "getnada.net"), Getnada("riau-net", "riau.net"))
        Registry.register(ChannelSpec("seokey-org", "seokey.org", "getnada.net"), Getnada("seokey-org", "seokey.org"))
        Registry.register(ChannelSpec("sulawesibarat-net", "sulawesibarat.net", "getnada.net"), Getnada("sulawesibarat-net", "sulawesibarat.net"))
        Registry.register(ChannelSpec("sulawesiselatan-net", "sulawesiselatan.net", "getnada.net"), Getnada("sulawesiselatan-net", "sulawesiselatan.net"))
        Registry.register(ChannelSpec("sulawesitengah-net", "sulawesitengah.net", "getnada.net"), Getnada("sulawesitengah-net", "sulawesitengah.net"))
        Registry.register(ChannelSpec("sulawesitenggara-net", "sulawesitenggara.net", "getnada.net"), Getnada("sulawesitenggara-net", "sulawesitenggara.net"))
        Registry.register(ChannelSpec("sumaterabarat-net", "sumaterabarat.net", "getnada.net"), Getnada("sumaterabarat-net", "sumaterabarat.net"))
        Registry.register(ChannelSpec("sumateraselatan-net", "sumateraselatan.net", "getnada.net"), Getnada("sumateraselatan-net", "sumateraselatan.net"))
        Registry.register(ChannelSpec("sumaterautara-net", "sumaterautara.net", "getnada.net"), Getnada("sumaterautara-net", "sumaterautara.net"))
        Registry.register(ChannelSpec("villatogel-com", "villatogel.com", "getnada.net"), Getnada("villatogel-com", "villatogel.com"))
        Registry.register(ChannelSpec("mail123", "Mail123", "mail123.fr"), Mail123)
        Registry.register(ChannelSpec("mail10s", "Mail10s", "mail10s.com"), Mail10s)
        Registry.register(ChannelSpec("webmailtemp", "WebMailTemp", "webmailtemp.com"), WebMailTemp)
        Registry.register(ChannelSpec("tempfastmail", "TempFastMail", "tempfastmail.com"), TempFastMail)
        Registry.register(ChannelSpec("1sec-mail", "1SecMail", "1sec-mail.com"), OneSecMail)
        Registry.register(ChannelSpec("fakemail", "FakeMail", "fakemail.net"), Fakemail)
        Registry.register(ChannelSpec("openinbox", "OpenInbox", "openinbox.io"), OpenInbox)
        Registry.register(ChannelSpec("inboxes", "Inboxes", "inboxes.com"), Inboxes)
        Registry.register(ChannelSpec("uncorreotemporal", "UnCorreoTemporal", "uncorreotemporal.com"), UnCorreoTemporal)
        Registry.register(ChannelSpec("awamail", "AwaMail", "awamail.com"), Awamail)
        Registry.register(ChannelSpec("mail-tm", "Mail.tm", "mail.tm"), MailTm("mail-tm", "https://api.mail.tm"))
        Registry.register(ChannelSpec("web-library-net", "web-library.net", "mail.tm"), MailTm("web-library-net", "https://api.mail.tm"))
        Registry.register(ChannelSpec("dropmail", "DropMail", "dropmail.me"), Dropmail)
        Registry.register(ChannelSpec("guerrillamail", "Guerrilla Mail", "guerrillamail.com"), GuerrillaMail("guerrillamail", "https://api.guerrillamail.com/ajax.php"))
        Registry.register(ChannelSpec("guerrillamail-com", "GuerrillaMail Root", "guerrillamail.com"), GuerrillaMail("guerrillamail-com", "https://guerrillamail.com/ajax.php"))
        Registry.register(ChannelSpec("maildrop", "Maildrop", "maildrop.cx"), Maildrop)
        Registry.register(ChannelSpec("smail-pw", "Smail.pw", "smail.pw"), SmailPw)
        Registry.register(ChannelSpec("vip-215", "VIP 215", "vip.215.im"), Vip215)
        Registry.register(ChannelSpec("fake-legal", "Fake Legal", "fake.legal"), FakeLegal("fake-legal", "fake.legal"))
        Registry.register(ChannelSpec("imgui-de", "imgui.de", "fake.legal"), FakeLegal("imgui-de", "imgui.de"))
        Registry.register(ChannelSpec("pulsewebmenu-de", "pulsewebmenu.de", "fake.legal"), FakeLegal("pulsewebmenu-de", "pulsewebmenu.de"))
        Registry.register(ChannelSpec("moakt", "Moakt", "moakt.com"), Moakt("moakt", "moakt.com"))
        Registry.register(ChannelSpec("drmail-in", "drmail.in", "moakt.com"), Moakt("drmail-in", "drmail.in"))
        Registry.register(ChannelSpec("teml-net", "teml.net", "moakt.com"), Moakt("teml-net", "teml.net"))
        Registry.register(ChannelSpec("tmpeml-com", "tmpeml.com", "moakt.com"), Moakt("tmpeml-com", "tmpeml.com"))
        Registry.register(ChannelSpec("tmpbox-net", "tmpbox.net", "moakt.com"), Moakt("tmpbox-net", "tmpbox.net"))
        Registry.register(ChannelSpec("moakt-cc", "moakt.cc", "moakt.com"), Moakt("moakt-cc", "moakt.cc"))
        Registry.register(ChannelSpec("disbox-net", "disbox.net", "moakt.com"), Moakt("disbox-net", "disbox.net"))
        Registry.register(ChannelSpec("tmpmail-org", "tmpmail.org", "moakt.com"), Moakt("tmpmail-org", "tmpmail.org"))
        Registry.register(ChannelSpec("tmpmail-net", "tmpmail.net", "moakt.com"), Moakt("tmpmail-net", "tmpmail.net"))
        Registry.register(ChannelSpec("tmails-net", "tmails.net", "moakt.com"), Moakt("tmails-net", "tmails.net"))
        Registry.register(ChannelSpec("disbox-org", "disbox.org", "moakt.com"), Moakt("disbox-org", "disbox.org"))
        Registry.register(ChannelSpec("moakt-co", "moakt.co", "moakt.com"), Moakt("moakt-co", "moakt.co"))
        Registry.register(ChannelSpec("moakt-ws", "moakt.ws", "moakt.com"), Moakt("moakt-ws", "moakt.ws"))
        Registry.register(ChannelSpec("tmail-ws", "tmail.ws", "moakt.com"), Moakt("tmail-ws", "tmail.ws"))
        Registry.register(ChannelSpec("bareed-ws", "bareed.ws", "moakt.com"), Moakt("bareed-ws", "bareed.ws"))
        Registry.register(ChannelSpec("email10min", "Email10Min", "email10min.com"), Email10min)
        Registry.register(ChannelSpec("mjj-cm", "MJJ Mail", "mjj.cm"), MjjCm)
        Registry.register(ChannelSpec("linshi-co", "临时Co", "linshi.co"), LinshiCo)
        Registry.register(ChannelSpec("harakirimail", "HarakiriMail", "harakirimail.com"), Harakirimail)
        Registry.register(ChannelSpec("jqkjqk-xyz", "jqkjqk.xyz", "mail.zhujump.com"), Zhujump("jqkjqk-xyz", "jqkjqk.xyz"))
        Registry.register(ChannelSpec("lyhlevi-com", "LyhLevi MoeMail", "lyhlevi.com"), Zhujump("lyhlevi-com", "lyhlevi.com", "https://lyhlevi.com", 24L * 60 * 60 * 1000))
        Registry.register(ChannelSpec("tempmail-plus", "TempMail Plus", "tempmail.plus"), TempMailPlus("tempmail-plus", "mailto.plus"))
        Registry.register(ChannelSpec("fexpost-com", "fexpost.com", "tempmail.plus"), TempMailPlus("fexpost-com", "fexpost.com"))
        Registry.register(ChannelSpec("fexbox-org", "fexbox.org", "tempmail.plus"), TempMailPlus("fexbox-org", "fexbox.org"))
        Registry.register(ChannelSpec("mailbox-in-ua", "mailbox.in.ua", "tempmail.plus"), TempMailPlus("mailbox-in-ua", "mailbox.in.ua"))
        Registry.register(ChannelSpec("rover-info", "rover.info", "tempmail.plus"), TempMailPlus("rover-info", "rover.info"))
        Registry.register(ChannelSpec("chitthi-in", "chitthi.in", "tempmail.plus"), TempMailPlus("chitthi-in", "chitthi.in"))
        Registry.register(ChannelSpec("fextemp-com", "fextemp.com", "tempmail.plus"), TempMailPlus("fextemp-com", "fextemp.com"))
        Registry.register(ChannelSpec("any-pink", "any.pink", "tempmail.plus"), TempMailPlus("any-pink", "any.pink"))
        Registry.register(ChannelSpec("merepost-com", "merepost.com", "tempmail.plus"), TempMailPlus("merepost-com", "merepost.com"))
        Registry.register(ChannelSpec("tempmail-lol-v2", "TempMail LOL V2", "tempmail.lol"), TempMailLolV2)
        Registry.register(ChannelSpec("tempgbox", "TempGBox", "tempgbox.net"), Tempgbox)
        Registry.register(ChannelSpec("emailnator", "Emailnator", "emailnator.com"), Emailnator)
        Registry.register(ChannelSpec("temporam", "Temporam", "temporam.com"), Temporam)
        Registry.register(ChannelSpec("neighbours", "Neighbours", "neighbours.sh"), Neighbours)
        Registry.register(ChannelSpec("sharklasers", "SharkLasers", "sharklasers.com"), GuerrillaMail("sharklasers", "https://www.sharklasers.com/ajax.php"))
        Registry.register(ChannelSpec("sharklasers-com", "SharkLasers Root", "sharklasers.com"), GuerrillaMail("sharklasers-com", "https://sharklasers.com/ajax.php"))
        Registry.register(ChannelSpec("grr-la", "Grr.la", "grr.la"), GuerrillaMail("grr-la", "https://www.grr.la/ajax.php"))
        Registry.register(ChannelSpec("grr-la-com", "Grr.la Root", "grr.la"), GuerrillaMail("grr-la-com", "https://grr.la/ajax.php"))
        Registry.register(ChannelSpec("guerrillamail-info", "GuerrillaMail Info", "guerrillamail.info"), GuerrillaMail("guerrillamail-info", "https://www.guerrillamail.info/ajax.php"))
        Registry.register(ChannelSpec("spam4me", "Spam4.me", "spam4.me"), GuerrillaMail("spam4me", "https://www.spam4.me/ajax.php"))
        Registry.register(ChannelSpec("guerrillamail-net", "GuerrillaMail Net", "guerrillamail.net"), GuerrillaMail("guerrillamail-net", "https://www.guerrillamail.net/ajax.php"))
        Registry.register(ChannelSpec("guerrillamail-org", "GuerrillaMail Org", "guerrillamail.org"), GuerrillaMail("guerrillamail-org", "https://www.guerrillamail.org/ajax.php"))
        Registry.register(ChannelSpec("guerrillamailblock", "GuerrillaMailBlock", "guerrillamailblock.com"), GuerrillaMail("guerrillamailblock", "https://www.guerrillamailblock.com/ajax.php"))
        Registry.register(ChannelSpec("guerrillamail-com-www", "GuerrillaMail WWW", "guerrillamail.com"), GuerrillaMail("guerrillamail-com-www", "https://www.guerrillamail.com/ajax.php"))
        Registry.register(ChannelSpec("m2u", "MailToYou", "m2u.io"), M2u)
        Registry.register(ChannelSpec("tempy-email", "Tempy Email", "tempy.email"), TempyEmail)
        Registry.register(ChannelSpec("fmail", "FMail", "fmail.men"), Fmail)
        Registry.register(ChannelSpec("ockito", "Ockito", "ockito.com"), Ockito)
        Registry.register(ChannelSpec("anonbox", "Anonbox", "anonbox.net"), Anonbox)
        Registry.register(ChannelSpec("duckmail", "DuckMail", "duckmail.sbs"), MailTm("duckmail", "https://api.duckmail.sbs"))
        Registry.register(ChannelSpec("mailinator", "Mailinator", "mailinator.com"), Mailinator("mailinator", "mailinator.com"))
        Registry.register(ChannelSpec("tempmail365", "Tempmail365", "https://tempmail365.cn"), Tempmail365)
        Registry.register(ChannelSpec("tempinbox", "TempInbox", "https://www.tempinbox.xyz"), Tempinbox)
        Registry.register(ChannelSpec("byom", "Byom", "byom.de"), Byom)
        Registry.register(ChannelSpec("anonymmail", "AnonymMail", "anonymmail.net"), Anonymmail)
        Registry.register(ChannelSpec("eyepaste", "EyePaste", "eyepaste.com"), Eyepaste)
        Registry.register(ChannelSpec("mail-sunls", "Mail Sunls", "mail.sunls.de"), MailSunls)
        Registry.register(ChannelSpec("expressinboxhub", "ExpressInboxHub", "expressinboxhub.com"), ExpressInboxHub)
        Registry.register(ChannelSpec("lroid", "Lroid", "lroid.com"), Lroid)
        Registry.register(ChannelSpec("haribu", "Haribu", "haribu.net"), Haribu)
        Registry.register(ChannelSpec("rootsh", "Rootsh(BccTo)", "rootsh.com"), Rootsh)
        Registry.register(ChannelSpec("fake-email-site", "FakeEmailSite", "fake-email.site"), FakeEmailSite)
        Registry.register(ChannelSpec("mohmal", "Mohmal", "mohmal.com"), Mohmal)
        Registry.register(ChannelSpec("mailgolem", "MailGolem", "mailgolem.com"), Mailgolem)
        Registry.register(ChannelSpec("best-temp-mail", "BestTempMail", "best-temp-mail.com"), BestTempMail)
        Registry.register(ChannelSpec("disposablemail-app", "DisposableMail", "disposablemail.app"), DisposablemailApp)
        Registry.register(ChannelSpec("mailtemp-cc", "MailTemp.cc", "mailtemp.cc"), MailtempCc)
        Registry.register(ChannelSpec("minuteinbox", "MinuteInbox", "minuteinbox.com"), Minuteinbox)
        Registry.register(ChannelSpec("mailcatch", "MailCatch", "mailcatch.com"), Mailcatch)
        Registry.register(ChannelSpec("tempemail-co", "TempEmail.co", "tempemail.co"), TempEmailCo)
        Registry.register(ChannelSpec("tempemails-net", "TempEmails.net", "tempemails.net"), TempEmailsNet)
        Registry.register(ChannelSpec("altmails", "AltMails", "tempmail.altmails.com"), Altmails)
        Registry.register(ChannelSpec("tempemail-info", "TempEmailInfo", "tempemail.info"), TempEmailInfo)
        Registry.register(ChannelSpec("smailpro", "SmailPro", "smailpro.com"), Smailpro)
        Registry.register(ChannelSpec("tempmailten", "TempMailTen", "tempmailten.com"), TempMailTen)
        Registry.register(ChannelSpec("maildrop-cc", "MailDrop.cc", "maildrop.cc"), MaildropCc)
        Registry.register(ChannelSpec("10minutemail-net", "10MinuteMail.net", "10minutemail.net"), TenminutemailNet)
        Registry.register(ChannelSpec("linshiyouxiang-net", "临时邮箱(linshiyouxiang)", "linshiyouxiang.net"), LinshiyouxiangNet)
        Registry.register(ChannelSpec("tempmail-fyi", "Temp-Mail.fyi", "temp-mail.fyi"), TempMailFyi)
        Registry.register(ChannelSpec("disposablemail-com", "DisposableMail.com", "disposablemail.com"), DisposablemailCom)
        Registry.register(ChannelSpec("tempp-mails", "TemppMails", "tempp-mails.com"), TemppMails)
        Registry.register(ChannelSpec("emailtemp-org", "EmailTemp", "emailtemp.org"), EmailtempOrg)
        Registry.register(ChannelSpec("mytempmail-cc", "MyTempMail.cc", "mytempmail.cc"), MytempMailCc)
        Registry.register(ChannelSpec("temp-mail-now", "TempMailNow", "temp-mail.now"), TempMailNow)
        Registry.register(ChannelSpec("mail-td", "Mail.td", "mail.td"), MailTd)
        Registry.register(ChannelSpec("mailhole-de", "Mailhole.de", "mailhole.de"), MailholeDe)
        Registry.register(ChannelSpec("tmail-link", "TMail.link", "tmail.link"), TmailLink)
        Registry.register(ChannelSpec("24mail-chacuo", "24Mail Chacuo", "24mail.chacuo.net"), Chacuo24Mail)
        Registry.register(ChannelSpec("nimail", "NiMail", "nimail.cn"), Nimail)
        Registry.register(ChannelSpec("freecustom", "FreeCustom.Email", "freecustom.email"), Freecustom)
        Registry.register(ChannelSpec("16888888-cyou", "Mailmomy (16888888.cyou)", "mailmomy.com"), Mailmomy("16888888-cyou", "16888888.cyou"))
        Registry.register(ChannelSpec("17666688-shop", "Mailmomy (17666688.shop)", "mailmomy.com"), Mailmomy("17666688-shop", "17666688.shop"))
        Registry.register(ChannelSpec("282mail-com", "Mailmomy (282mail.com)", "mailmomy.com"), Mailmomy("282mail-com", "282mail.com"))
        Registry.register(ChannelSpec("blackhole-djurby-se", "Mailinator (blackhole.djurby.se)", "mailinator.com"), Mailinator("blackhole-djurby-se", "blackhole.djurby.se"))
        Registry.register(ChannelSpec("block-bdea-cc", "Mailinator (block.bdea.cc)", "mailinator.com"), Mailinator("block-bdea-cc", "block.bdea.cc"))
        Registry.register(ChannelSpec("bsdu32-buzz", "Mailmomy (bsdu32.buzz)", "mailmomy.com"), Mailmomy("bsdu32-buzz", "bsdu32.buzz"))
        Registry.register(ChannelSpec("b-smelly-cc", "Mailinator (b.smelly.cc)", "mailinator.com"), Mailinator("b-smelly-cc", "b.smelly.cc"))
        Registry.register(ChannelSpec("carlton183-changeip-net", "Mailinator (183carlton.changeip.net)", "mailinator.com"), Mailinator("carlton183-changeip-net", "183carlton.changeip.net"))
        Registry.register(ChannelSpec("dea-soon-it", "Mailinator (dea.soon.it)", "mailinator.com"), Mailinator("dea-soon-it", "dea.soon.it"))
        Registry.register(ChannelSpec("disposable-al-sudani-com", "Mailinator (disposable.al-sudani.com)", "mailinator.com"), Mailinator("disposable-al-sudani-com", "disposable.al-sudani.com"))
        Registry.register(ChannelSpec("disposable-nogonad-nl", "Mailinator (disposable.nogonad.nl)", "mailinator.com"), Mailinator("disposable-nogonad-nl", "disposable.nogonad.nl"))
        Registry.register(ChannelSpec("doxu243-buzz", "Mailmomy (doxu243.buzz)", "mailmomy.com"), Mailmomy("doxu243-buzz", "doxu243.buzz"))
        Registry.register(ChannelSpec("easyme-pro", "Mailmomy (easyme.pro)", "mailmomy.com"), Mailmomy("easyme-pro", "easyme.pro"))
        Registry.register(ChannelSpec("ebs-com-ar", "Mailinator (ebs.com.ar)", "mailinator.com"), Mailinator("ebs-com-ar", "ebs.com.ar"))
        Registry.register(ChannelSpec("etgdev-de", "Mailinator (etgdev.de)", "mailinator.com"), Mailinator("etgdev-de", "etgdev.de"))
        Registry.register(ChannelSpec("evergreenco-shop", "Mailmomy (evergreenco.shop)", "mailmomy.com"), Mailmomy("evergreenco-shop", "evergreenco.shop"))
        Registry.register(ChannelSpec("fwd2m-eszett-es", "Mailinator (fwd2m.eszett.es)", "mailinator.com"), Mailinator("fwd2m-eszett-es", "fwd2m.eszett.es"))
        Registry.register(ChannelSpec("jama-trenet-eu", "Mailinator (jama.trenet.eu)", "mailinator.com"), Mailinator("jama-trenet-eu", "jama.trenet.eu"))
        Registry.register(ChannelSpec("j-fairuse-org", "Mailinator (j.fairuse.org)", "mailinator.com"), Mailinator("j-fairuse-org", "j.fairuse.org"))
        Registry.register(ChannelSpec("layueming-pics", "Mailmomy (layueming.pics)", "mailmomy.com"), Mailmomy("layueming-pics", "layueming.pics"))
        Registry.register(ChannelSpec("m-887-at", "Mailinator (m.887.at)", "mailinator.com"), Mailinator("m-887-at", "m.887.at"))
        Registry.register(ChannelSpec("m8r-davidfuhr-de", "Mailinator (m8r.davidfuhr.de)", "mailinator.com"), Mailinator("m8r-davidfuhr-de", "m8r.davidfuhr.de"))
        Registry.register(ChannelSpec("m8r-mcasal-com", "Mailinator (m8r.mcasal.com)", "mailinator.com"), Mailinator("m8r-mcasal-com", "m8r.mcasal.com"))
        Registry.register(ChannelSpec("mail-bentrask-com", "Mailinator (mail.bentrask.com)", "mailinator.com"), Mailinator("mail-bentrask-com", "mail.bentrask.com"))
        Registry.register(ChannelSpec("mail-fsmash-org", "Mailinator (mail.fsmash.org)", "mailinator.com"), Mailinator("mail-fsmash-org", "mail.fsmash.org"))
        Registry.register(ChannelSpec("mailinatorzz-mooo-com", "Mailinator (mailinatorzz.mooo.com)", "mailinator.com"), Mailinator("mailinatorzz-mooo-com", "mailinatorzz.mooo.com"))
        Registry.register(ChannelSpec("mi-meon-be", "Mailinator (mi.meon.be)", "mailinator.com"), Mailinator("mi-meon-be", "mi.meon.be"))
        Registry.register(ChannelSpec("mingyuekeji-online", "Mailmomy (mingyuekeji.online)", "mailmomy.com"), Mailmomy("mingyuekeji-online", "mingyuekeji.online"))
        Registry.register(ChannelSpec("mingyueming-click", "Mailmomy (mingyueming.click)", "mailmomy.com"), Mailmomy("mingyueming-click", "mingyueming.click"))
        Registry.register(ChannelSpec("mingyueming-shop", "Mailmomy (mingyueming.shop)", "mailmomy.com"), Mailmomy("mingyueming-shop", "mingyueming.shop"))
        Registry.register(ChannelSpec("mingyukeji-lol", "Mailmomy (mingyukeji.lol)", "mailmomy.com"), Mailmomy("mingyukeji-lol", "mingyukeji.lol"))
        Registry.register(ChannelSpec("mn-curppa-com", "Mailinator (mn.curppa.com)", "mailinator.com"), Mailinator("mn-curppa-com", "mn.curppa.com"))
        Registry.register(ChannelSpec("m-nik-me", "Mailinator (m.nik.me)", "mailinator.com"), Mailinator("m-nik-me", "m.nik.me"))
        Registry.register(ChannelSpec("mtmdev-com", "Mailinator (mtmdev.com)", "mailinator.com"), Mailinator("mtmdev-com", "mtmdev.com"))
        Registry.register(ChannelSpec("nospam-thurstons-us", "Mailinator (nospam.thurstons.us)", "mailinator.com"), Mailinator("nospam-thurstons-us", "nospam.thurstons.us"))
        Registry.register(ChannelSpec("notfond-404-mn", "Mailinator (notfond.404.mn)", "mailinator.com"), Mailinator("notfond-404-mn", "notfond.404.mn"))
        Registry.register(ChannelSpec("null-k3vin-net", "Mailinator (null.k3vin.net)", "mailinator.com"), Mailinator("null-k3vin-net", "null.k3vin.net"))
        Registry.register(ChannelSpec("nuxh62-space", "Mailmomy (nuxh62.space)", "mailmomy.com"), Mailmomy("nuxh62-space", "nuxh62.space"))
        Registry.register(ChannelSpec("proid-cloud-ip-cc", "Mailmomy (proid.cloud-ip.cc)", "mailmomy.com"), Mailmomy("proid-cloud-ip-cc", "proid.cloud-ip.cc"))
        Registry.register(ChannelSpec("ramjane-mooo-com", "Mailinator (ramjane.mooo.com)", "mailinator.com"), Mailinator("ramjane-mooo-com", "ramjane.mooo.com"))
        Registry.register(ChannelSpec("rauxa-seny-cat", "Mailinator (rauxa.seny.cat)", "mailinator.com"), Mailinator("rauxa-seny-cat", "rauxa.seny.cat"))
        Registry.register(ChannelSpec("really-istrash-com", "Mailinator (really.istrash.com)", "mailinator.com"), Mailinator("really-istrash-com", "really.istrash.com"))
        Registry.register(ChannelSpec("sbook-pics", "Mailmomy (sbook.pics)", "mailmomy.com"), Mailmomy("sbook-pics", "sbook.pics"))
        Registry.register(ChannelSpec("spam-hortuk-ovh", "Mailinator (spam.hortuk.ovh)", "mailinator.com"), Mailinator("spam-hortuk-ovh", "spam.hortuk.ovh"))
        Registry.register(ChannelSpec("sp-woot-at", "Mailinator (sp.woot.at)", "mailinator.com"), Mailinator("sp-woot-at", "sp.woot.at"))
        Registry.register(ChannelSpec("test-unergie-com", "Mailinator (test.unergie.com)", "mailinator.com"), Mailinator("test-unergie-com", "test.unergie.com"))
        Registry.register(ChannelSpec("torch-yi-org", "Mailinator (torch.yi.org)", "mailinator.com"), Mailinator("torch-yi-org", "torch.yi.org"))
        Registry.register(ChannelSpec("t-zibet-net", "Mailinator (t.zibet.net)", "mailinator.com"), Mailinator("t-zibet-net", "t.zibet.net"))
        Registry.register(ChannelSpec("xue32-buzz", "Mailmomy (xue32.buzz)", "mailmomy.com"), Mailmomy("xue32-buzz", "xue32.buzz"))
        Registry.register(ChannelSpec("apihz", "ApiHz TempMail", "apihz.cn"), Apihz)
        Registry.register(ChannelSpec("sogetthis-com", "Mailinator (sogetthis.com)", "mailinator.com"), Mailinator("sogetthis-com", "sogetthis.com"))
        Registry.register(ChannelSpec("bobmail-info", "Mailinator (bobmail.info)", "mailinator.com"), Mailinator("bobmail-info", "bobmail.info"))
        Registry.register(ChannelSpec("suremail-info", "Mailinator (suremail.info)", "mailinator.com"), Mailinator("suremail-info", "suremail.info"))
        Registry.register(ChannelSpec("binkmail-com", "Mailinator (binkmail.com)", "mailinator.com"), Mailinator("binkmail-com", "binkmail.com"))
        Registry.register(ChannelSpec("veryrealemail-com", "Mailinator (veryrealemail.com)", "mailinator.com"), Mailinator("veryrealemail-com", "veryrealemail.com"))
        Registry.register(ChannelSpec("mailmomy", "Mailmomy", "mailmomy.com"), Mailmomy("mailmomy", "mailmomy.com"))
        Registry.register(ChannelSpec("chammy-info", "Mailinator (chammy.info)", "mailinator.com"), Mailinator("chammy-info", "chammy.info"))
        Registry.register(ChannelSpec("thisisnotmyrealemail-com", "Mailinator (thisisnotmyrealemail.com)", "mailinator.com"), Mailinator("thisisnotmyrealemail-com", "thisisnotmyrealemail.com"))
        Registry.register(ChannelSpec("notmailinator-com", "Mailinator (notmailinator.com)", "mailinator.com"), Mailinator("notmailinator-com", "notmailinator.com"))
        Registry.register(ChannelSpec("spamhereplease-com", "Mailinator (spamhereplease.com)", "mailinator.com"), Mailinator("spamhereplease-com", "spamhereplease.com"))
        Registry.register(ChannelSpec("sendspamhere-com", "Mailinator (sendspamhere.com)", "mailinator.com"), Mailinator("sendspamhere-com", "sendspamhere.com"))
        Registry.register(ChannelSpec("sendfree-org", "Mailinator (sendfree.org)", "mailinator.com"), Mailinator("sendfree-org", "sendfree.org"))
        Registry.register(ChannelSpec("junk-beats-org", "Mailinator (junk.beats.org)", "mailinator.com"), Mailinator("junk-beats-org", "junk.beats.org"))
        Registry.register(ChannelSpec("junk-ihmehl-com", "Mailinator (junk.ihmehl.com)", "mailinator.com"), Mailinator("junk-ihmehl-com", "junk.ihmehl.com"))
        Registry.register(ChannelSpec("junk-noplay-org", "Mailinator (junk.noplay.org)", "mailinator.com"), Mailinator("junk-noplay-org", "junk.noplay.org"))
        Registry.register(ChannelSpec("junk-vanillasystem-com", "Mailinator (junk.vanillasystem.com)", "mailinator.com"), Mailinator("junk-vanillasystem-com", "junk.vanillasystem.com"))
        Registry.register(ChannelSpec("spam-jasonpearce-com", "Mailinator (spam.jasonpearce.com)", "mailinator.com"), Mailinator("spam-jasonpearce-com", "spam.jasonpearce.com"))
        Registry.register(ChannelSpec("fish-skytale-net", "Mailinator (fish.skytale.net)", "mailinator.com"), Mailinator("fish-skytale-net", "fish.skytale.net"))
        Registry.register(ChannelSpec("spam-mccrew-com", "Mailinator (spam.mccrew.com)", "mailinator.com"), Mailinator("spam-mccrew-com", "spam.mccrew.com"))
        Registry.register(ChannelSpec("dropmail-click", "DropMail.click", "dropmail.click"), DropmailClick)
        Registry.register(ChannelSpec("spam-coroiu-com", "Mailinator (spam.coroiu.com)", "mailinator.com"), Mailinator("spam-coroiu-com", "spam.coroiu.com"))
        Registry.register(ChannelSpec("spam-deluser-net", "Mailinator (spam.deluser.net)", "mailinator.com"), Mailinator("spam-deluser-net", "spam.deluser.net"))
        Registry.register(ChannelSpec("spam-dhsf-net", "Mailinator (spam.dhsf.net)", "mailinator.com"), Mailinator("spam-dhsf-net", "spam.dhsf.net"))
        Registry.register(ChannelSpec("spam-lucatnt-com", "Mailinator (spam.lucatnt.com)", "mailinator.com"), Mailinator("spam-lucatnt-com", "spam.lucatnt.com"))
        Registry.register(ChannelSpec("spam-lyceum-life-com-ru", "Mailinator (spam.lyceum-life.com.ru)", "mailinator.com"), Mailinator("spam-lyceum-life-com-ru", "spam.lyceum-life.com.ru"))
        Registry.register(ChannelSpec("spam-netpirates-net", "Mailinator (spam.netpirates.net)", "mailinator.com"), Mailinator("spam-netpirates-net", "spam.netpirates.net"))
        Registry.register(ChannelSpec("spam-no-ip-net", "Mailinator (spam.no-ip.net)", "mailinator.com"), Mailinator("spam-no-ip-net", "spam.no-ip.net"))
        Registry.register(ChannelSpec("spam-ozh-org", "Mailinator (spam.ozh.org)", "mailinator.com"), Mailinator("spam-ozh-org", "spam.ozh.org"))
        Registry.register(ChannelSpec("spam-pyphus-org", "Mailinator (spam.pyphus.org)", "mailinator.com"), Mailinator("spam-pyphus-org", "spam.pyphus.org"))
        Registry.register(ChannelSpec("spam-shep-pw", "Mailinator (spam.shep.pw)", "mailinator.com"), Mailinator("spam-shep-pw", "spam.shep.pw"))
        Registry.register(ChannelSpec("spam-wtf-at", "Mailinator (spam.wtf.at)", "mailinator.com"), Mailinator("spam-wtf-at", "spam.wtf.at"))
        Registry.register(ChannelSpec("spam-wulczer-org", "Mailinator (spam.wulczer.org)", "mailinator.com"), Mailinator("spam-wulczer-org", "spam.wulczer.org"))
        Registry.register(ChannelSpec("crap-kakadua-net", "Mailinator (crap.kakadua.net)", "mailinator.com"), Mailinator("crap-kakadua-net", "crap.kakadua.net"))
        Registry.register(ChannelSpec("spam-janlugt-nl", "Mailinator (spam.janlugt.nl)", "mailinator.com"), Mailinator("spam-janlugt-nl", "spam.janlugt.nl"))
        Registry.register(ChannelSpec("min-burningfish-net", "Mailinator (min.burningfish.net)", "mailinator.com"), Mailinator("min-burningfish-net", "min.burningfish.net"))
        Registry.register(ChannelSpec("sink-fblay-com", "Mailinator (sink.fblay.com)", "mailinator.com"), Mailinator("sink-fblay-com", "sink.fblay.com"))
        Registry.register(ChannelSpec("tempgmailer", "TempGmailer", "tempgmailer.com"), TempGmailer)
        Registry.register(ChannelSpec("temp-mail-org", "Temp-Mail.org", "temp-mail.org"), TempMailOrg)
        Registry.register(ChannelSpec("xkx-me", "XKX.me", "xkx.me"), XkxMe)
        Registry.register(ChannelSpec("gonebox-email", "Gonebox Email", "gonebox.email"), GoneboxEmail)
        Registry.register(ChannelSpec("mailcat-ai", "Mailcat AI", "mailcat.ai"), MailcatAi)
        Registry.register(ChannelSpec("tempgo-email", "TempGo Email", "tempgo.email"), TempGoEmail)
        Registry.register(ChannelSpec("restmail-net", "Restmail.net", "restmail.net"), RestmailNet)
        Registry.register(ChannelSpec("dropmail-me", "DropMail.me", "dropmail.me"), DropmailMe)
        Registry.register(ChannelSpec("ten-minute-mail-net", "10MinuteMail.net", "10minutemail.net"), TenminutemailNet)
    }
}
