# frozen_string_literal: true
#
# 渠道元数据（有序，权威来源 .channel_meta.json，顺序与 baseline 逐行一致）
# 每项为 [slug, name, website]，注册表按此顺序枚举，顺序为硬约束。
#
module TempmailSdk
  # 279 个渠道的有序元数据
  CHANNEL_DATA = [
    ["tempmail", "TempMail", "tempmail.ing"],
    ["tempmail-cn", "TempMail CN", "tempmail.cn"],
    ["ta-easy", "TA Easy", "ta-easy.com"],
    ["10minute-one", "10 Minute Email", "10minutemail.one"],
    ["xghff-com", "xghff.com", "10minutemail.one"],
    ["oqqaj-com", "oqqaj.com", "10minutemail.one"],
    ["psovv-com", "psovv.com", "10minutemail.one"],
    ["dbwot-com", "dbwot.com", "10minutemail.one"],
    ["ygwpr-com", "ygwpr.com", "10minutemail.one"],
    ["imxwe-com", "imxwe.com", "10minutemail.one"],
    ["linshiyou", "临时邮", "linshiyou.com"],
    ["mffac", "MFFAC", "mffac.com"],
    ["tempmail-lol", "TempMail LOL", "tempmail.lol"],
    ["chatgpt-org-uk", "ChatGPT Mail", "mail.chatgpt.org.uk"],
    ["temp-mail-io", "Temp-Mail.io", "temp-mail.io"],
    ["mail-cx", "Mail.cx", "mail.cx"],
    ["ddker-com", "ddker.com", "mail.cx"],
    ["catchmail", "Catchmail", "catchmail.io"],
    ["catchmail-mailistry", "Catchmail Mailistry", "mailistry.com"],
    ["catchmail-zeppost", "Catchmail Zeppost", "zeppost.com"],
    ["mailforspam", "MailForSpam", "mailforspam.com"],
    ["mailforspam-tempmail-io", "MailForSpam TempMail.io", "tempmail.io"],
    ["mailforspam-disposable", "MailForSpam Disposable", "disposable.email"],
    ["tempmailc", "TempMailC", "tempmailc.com"],
    ["mailnesia", "Mailnesia", "mailnesia.com"],
    ["throwawaymail", "ThrowawayMail", "throwawaymail.app"],
    ["tempmail-fish", "TempMail Fish", "tempmail.fish"],
    ["neighbours-sh", "Neighbours", "neighbours.sh"],
    ["shitty-email", "shitty.email", "shitty.email"],
    ["tempmailpro", "TempMail Pro", "tempmailpro.us"],
    ["devmail-uk", "DevMail UK", "devmail.uk"],
    ["inboxkitten", "InboxKitten", "inboxkitten.com"],
    ["cleantempmail", "CleanTempMail", "cleantempmail.com"],
    ["getnada", "GetNada", "getnada.net"],
    ["1vpn-net", "1vpn.net", "getnada.net"],
    ["abematv-com", "abematv.com", "getnada.net"],
    ["abematv-net", "abematv.net", "getnada.net"],
    ["abematv-org", "abematv.org", "getnada.net"],
    ["aceh-cc", "aceh.cc", "getnada.net"],
    ["bangkabelitung-net", "bangkabelitung.net", "getnada.net"],
    ["cctruyen-com", "cctruyen.com", "getnada.net"],
    ["getnada-com", "getnada.com", "getnada.net"],
    ["getnada-email", "getnada.email", "getnada.net"],
    ["getnada-net", "getnada.net", "getnada.net"],
    ["jawatengah-net", "jawatengah.net", "getnada.net"],
    ["jawatimur-net", "jawatimur.net", "getnada.net"],
    ["kalimantanbarat-net", "kalimantanbarat.net", "getnada.net"],
    ["kalimantanselatan-net", "kalimantanselatan.net", "getnada.net"],
    ["kalimantantengah-net", "kalimantantengah.net", "getnada.net"],
    ["kalimantantimur-net", "kalimantantimur.net", "getnada.net"],
    ["kalimantanutara-net", "kalimantanutara.net", "getnada.net"],
    ["kepulauanriau-net", "kepulauanriau.net", "getnada.net"],
    ["luxury345-com", "luxury345.com", "getnada.net"],
    ["malukuutara-net", "malukuutara.net", "getnada.net"],
    ["nusatenggarabarat-net", "nusatenggarabarat.net", "getnada.net"],
    ["nusatenggaratimur-net", "nusatenggaratimur.net", "getnada.net"],
    ["papuabarat-net", "papuabarat.net", "getnada.net"],
    ["papuabaratdaya-net", "papuabaratdaya.net", "getnada.net"],
    ["papuaselatan-net", "papuaselatan.net", "getnada.net"],
    ["pehol-com", "pehol.com", "getnada.net"],
    ["ptruyen-com", "ptruyen.com", "getnada.net"],
    ["pulaubali-net", "pulaubali.net", "getnada.net"],
    ["riau-net", "riau.net", "getnada.net"],
    ["seokey-org", "seokey.org", "getnada.net"],
    ["sulawesibarat-net", "sulawesibarat.net", "getnada.net"],
    ["sulawesiselatan-net", "sulawesiselatan.net", "getnada.net"],
    ["sulawesitengah-net", "sulawesitengah.net", "getnada.net"],
    ["sulawesitenggara-net", "sulawesitenggara.net", "getnada.net"],
    ["sumaterabarat-net", "sumaterabarat.net", "getnada.net"],
    ["sumateraselatan-net", "sumateraselatan.net", "getnada.net"],
    ["sumaterautara-net", "sumaterautara.net", "getnada.net"],
    ["villatogel-com", "villatogel.com", "getnada.net"],
    ["mail123", "Mail123", "mail123.fr"],
    ["mail10s", "Mail10s", "mail10s.com"],
    ["webmailtemp", "WebMailTemp", "webmailtemp.com"],
    ["tempfastmail", "TempFastMail", "tempfastmail.com"],
    ["1sec-mail", "1SecMail", "1sec-mail.com"],
    ["fakemail", "FakeMail", "fakemail.net"],
    ["openinbox", "OpenInbox", "openinbox.io"],
    ["inboxes", "Inboxes", "inboxes.com"],
    ["uncorreotemporal", "UnCorreoTemporal", "uncorreotemporal.com"],
    ["awamail", "AwaMail", "awamail.com"],
    ["mail-tm", "Mail.tm", "mail.tm"],
    ["web-library-net", "web-library.net", "mail.tm"],
    ["dropmail", "DropMail", "dropmail.me"],
    ["guerrillamail", "Guerrilla Mail", "guerrillamail.com"],
    ["guerrillamail-com", "GuerrillaMail Root", "guerrillamail.com"],
    ["maildrop", "Maildrop", "maildrop.cx"],
    ["smail-pw", "Smail.pw", "smail.pw"],
    ["vip-215", "VIP 215", "vip.215.im"],
    ["fake-legal", "Fake Legal", "fake.legal"],
    ["imgui-de", "imgui.de", "fake.legal"],
    ["pulsewebmenu-de", "pulsewebmenu.de", "fake.legal"],
    ["moakt", "Moakt", "moakt.com"],
    ["drmail-in", "drmail.in", "moakt.com"],
    ["teml-net", "teml.net", "moakt.com"],
    ["tmpeml-com", "tmpeml.com", "moakt.com"],
    ["tmpbox-net", "tmpbox.net", "moakt.com"],
    ["moakt-cc", "moakt.cc", "moakt.com"],
    ["disbox-net", "disbox.net", "moakt.com"],
    ["tmpmail-org", "tmpmail.org", "moakt.com"],
    ["tmpmail-net", "tmpmail.net", "moakt.com"],
    ["tmails-net", "tmails.net", "moakt.com"],
    ["disbox-org", "disbox.org", "moakt.com"],
    ["moakt-co", "moakt.co", "moakt.com"],
    ["moakt-ws", "moakt.ws", "moakt.com"],
    ["tmail-ws", "tmail.ws", "moakt.com"],
    ["bareed-ws", "bareed.ws", "moakt.com"],
    ["email10min", "Email10Min", "email10min.com"],
    ["mjj-cm", "MJJ Mail", "mjj.cm"],
    ["linshi-co", "临时Co", "linshi.co"],
    ["harakirimail", "HarakiriMail", "harakirimail.com"],
    ["jqkjqk-xyz", "jqkjqk.xyz", "mail.zhujump.com"],
    ["lyhlevi-com", "LyhLevi MoeMail", "lyhlevi.com"],
    ["tempmail-plus", "TempMail Plus", "tempmail.plus"],
    ["fexpost-com", "fexpost.com", "tempmail.plus"],
    ["fexbox-org", "fexbox.org", "tempmail.plus"],
    ["mailbox-in-ua", "mailbox.in.ua", "tempmail.plus"],
    ["rover-info", "rover.info", "tempmail.plus"],
    ["chitthi-in", "chitthi.in", "tempmail.plus"],
    ["fextemp-com", "fextemp.com", "tempmail.plus"],
    ["any-pink", "any.pink", "tempmail.plus"],
    ["merepost-com", "merepost.com", "tempmail.plus"],
    ["tempmail-lol-v2", "TempMail LOL V2", "tempmail.lol"],
    ["tempgbox", "TempGBox", "tempgbox.net"],
    ["emailnator", "Emailnator", "emailnator.com"],
    ["temporam", "Temporam", "temporam.com"],
    ["neighbours", "Neighbours", "neighbours.sh"],
    ["sharklasers", "SharkLasers", "sharklasers.com"],
    ["sharklasers-com", "SharkLasers Root", "sharklasers.com"],
    ["grr-la", "Grr.la", "grr.la"],
    ["grr-la-com", "Grr.la Root", "grr.la"],
    ["guerrillamail-info", "GuerrillaMail Info", "guerrillamail.info"],
    ["spam4me", "Spam4.me", "spam4.me"],
    ["guerrillamail-net", "GuerrillaMail Net", "guerrillamail.net"],
    ["guerrillamail-org", "GuerrillaMail Org", "guerrillamail.org"],
    ["guerrillamailblock", "GuerrillaMailBlock", "guerrillamailblock.com"],
    ["guerrillamail-com-www", "GuerrillaMail WWW", "guerrillamail.com"],
    ["m2u", "MailToYou", "m2u.io"],
    ["tempy-email", "Tempy Email", "tempy.email"],
    ["fmail", "FMail", "fmail.men"],
    ["ockito", "Ockito", "ockito.com"],
    ["anonbox", "Anonbox", "anonbox.net"],
    ["duckmail", "DuckMail", "duckmail.sbs"],
    ["mailinator", "Mailinator", "mailinator.com"],
    ["tempmail365", "Tempmail365", "https://tempmail365.cn"],
    ["tempinbox", "TempInbox", "https://www.tempinbox.xyz"],
    ["byom", "Byom", "byom.de"],
    ["anonymmail", "AnonymMail", "anonymmail.net"],
    ["eyepaste", "EyePaste", "eyepaste.com"],
    ["mail-sunls", "Mail Sunls", "mail.sunls.de"],
    ["expressinboxhub", "ExpressInboxHub", "expressinboxhub.com"],
    ["lroid", "Lroid", "lroid.com"],
    ["haribu", "Haribu", "haribu.net"],
    ["rootsh", "Rootsh(BccTo)", "rootsh.com"],
    ["fake-email-site", "FakeEmailSite", "fake-email.site"],
    ["mohmal", "Mohmal", "mohmal.com"],
    ["mailgolem", "MailGolem", "mailgolem.com"],
    ["best-temp-mail", "BestTempMail", "best-temp-mail.com"],
    ["disposablemail-app", "DisposableMail", "disposablemail.app"],
    ["mailtemp-cc", "MailTemp.cc", "mailtemp.cc"],
    ["minuteinbox", "MinuteInbox", "minuteinbox.com"],
    ["mailcatch", "MailCatch", "mailcatch.com"],
    ["tempemail-co", "TempEmail.co", "tempemail.co"],
    ["tempemails-net", "TempEmails.net", "tempemails.net"],
    ["altmails", "AltMails", "tempmail.altmails.com"],
    ["tempemail-info", "TempEmailInfo", "tempemail.info"],
    ["smailpro", "SmailPro", "smailpro.com"],
    ["tempmailten", "TempMailTen", "tempmailten.com"],
    ["maildrop-cc", "MailDrop.cc", "maildrop.cc"],
    ["10minutemail-net", "10MinuteMail.net", "10minutemail.net"],
    ["linshiyouxiang-net", "临时邮箱(linshiyouxiang)", "linshiyouxiang.net"],
    ["tempmail-fyi", "Temp-Mail.fyi", "temp-mail.fyi"],
    ["disposablemail-com", "DisposableMail.com", "disposablemail.com"],
    ["tempp-mails", "TemppMails", "tempp-mails.com"],
    ["emailtemp-org", "EmailTemp", "emailtemp.org"],
    ["mytempmail-cc", "MyTempMail.cc", "mytempmail.cc"],
    ["temp-mail-now", "TempMailNow", "temp-mail.now"],
    ["mail-td", "Mail.td", "mail.td"],
    ["mailhole-de", "Mailhole.de", "mailhole.de"],
    ["tmail-link", "TMail.link", "tmail.link"],
    ["24mail-chacuo", "24Mail Chacuo", "24mail.chacuo.net"],
    ["nimail", "NiMail", "nimail.cn"],
    ["freecustom", "FreeCustom.Email", "freecustom.email"],
    ["16888888-cyou", "Mailmomy (16888888.cyou)", "mailmomy.com"],
    ["17666688-shop", "Mailmomy (17666688.shop)", "mailmomy.com"],
    ["282mail-com", "Mailmomy (282mail.com)", "mailmomy.com"],
    ["blackhole-djurby-se", "Mailinator (blackhole.djurby.se)", "mailinator.com"],
    ["block-bdea-cc", "Mailinator (block.bdea.cc)", "mailinator.com"],
    ["bsdu32-buzz", "Mailmomy (bsdu32.buzz)", "mailmomy.com"],
    ["b-smelly-cc", "Mailinator (b.smelly.cc)", "mailinator.com"],
    ["carlton183-changeip-net", "Mailinator (183carlton.changeip.net)", "mailinator.com"],
    ["dea-soon-it", "Mailinator (dea.soon.it)", "mailinator.com"],
    ["disposable-al-sudani-com", "Mailinator (disposable.al-sudani.com)", "mailinator.com"],
    ["disposable-nogonad-nl", "Mailinator (disposable.nogonad.nl)", "mailinator.com"],
    ["doxu243-buzz", "Mailmomy (doxu243.buzz)", "mailmomy.com"],
    ["easyme-pro", "Mailmomy (easyme.pro)", "mailmomy.com"],
    ["ebs-com-ar", "Mailinator (ebs.com.ar)", "mailinator.com"],
    ["etgdev-de", "Mailinator (etgdev.de)", "mailinator.com"],
    ["evergreenco-shop", "Mailmomy (evergreenco.shop)", "mailmomy.com"],
    ["fwd2m-eszett-es", "Mailinator (fwd2m.eszett.es)", "mailinator.com"],
    ["jama-trenet-eu", "Mailinator (jama.trenet.eu)", "mailinator.com"],
    ["j-fairuse-org", "Mailinator (j.fairuse.org)", "mailinator.com"],
    ["layueming-pics", "Mailmomy (layueming.pics)", "mailmomy.com"],
    ["m-887-at", "Mailinator (m.887.at)", "mailinator.com"],
    ["m8r-davidfuhr-de", "Mailinator (m8r.davidfuhr.de)", "mailinator.com"],
    ["m8r-mcasal-com", "Mailinator (m8r.mcasal.com)", "mailinator.com"],
    ["mail-bentrask-com", "Mailinator (mail.bentrask.com)", "mailinator.com"],
    ["mail-fsmash-org", "Mailinator (mail.fsmash.org)", "mailinator.com"],
    ["mailinatorzz-mooo-com", "Mailinator (mailinatorzz.mooo.com)", "mailinator.com"],
    ["mi-meon-be", "Mailinator (mi.meon.be)", "mailinator.com"],
    ["mingyuekeji-online", "Mailmomy (mingyuekeji.online)", "mailmomy.com"],
    ["mingyueming-click", "Mailmomy (mingyueming.click)", "mailmomy.com"],
    ["mingyueming-shop", "Mailmomy (mingyueming.shop)", "mailmomy.com"],
    ["mingyukeji-lol", "Mailmomy (mingyukeji.lol)", "mailmomy.com"],
    ["mn-curppa-com", "Mailinator (mn.curppa.com)", "mailinator.com"],
    ["m-nik-me", "Mailinator (m.nik.me)", "mailinator.com"],
    ["mtmdev-com", "Mailinator (mtmdev.com)", "mailinator.com"],
    ["nospam-thurstons-us", "Mailinator (nospam.thurstons.us)", "mailinator.com"],
    ["notfond-404-mn", "Mailinator (notfond.404.mn)", "mailinator.com"],
    ["null-k3vin-net", "Mailinator (null.k3vin.net)", "mailinator.com"],
    ["nuxh62-space", "Mailmomy (nuxh62.space)", "mailmomy.com"],
    ["proid-cloud-ip-cc", "Mailmomy (proid.cloud-ip.cc)", "mailmomy.com"],
    ["ramjane-mooo-com", "Mailinator (ramjane.mooo.com)", "mailinator.com"],
    ["rauxa-seny-cat", "Mailinator (rauxa.seny.cat)", "mailinator.com"],
    ["really-istrash-com", "Mailinator (really.istrash.com)", "mailinator.com"],
    ["sbook-pics", "Mailmomy (sbook.pics)", "mailmomy.com"],
    ["spam-hortuk-ovh", "Mailinator (spam.hortuk.ovh)", "mailinator.com"],
    ["sp-woot-at", "Mailinator (sp.woot.at)", "mailinator.com"],
    ["test-unergie-com", "Mailinator (test.unergie.com)", "mailinator.com"],
    ["torch-yi-org", "Mailinator (torch.yi.org)", "mailinator.com"],
    ["t-zibet-net", "Mailinator (t.zibet.net)", "mailinator.com"],
    ["xue32-buzz", "Mailmomy (xue32.buzz)", "mailmomy.com"],
    ["apihz", "ApiHz TempMail", "apihz.cn"],
    ["sogetthis-com", "Mailinator (sogetthis.com)", "mailinator.com"],
    ["bobmail-info", "Mailinator (bobmail.info)", "mailinator.com"],
    ["suremail-info", "Mailinator (suremail.info)", "mailinator.com"],
    ["binkmail-com", "Mailinator (binkmail.com)", "mailinator.com"],
    ["veryrealemail-com", "Mailinator (veryrealemail.com)", "mailinator.com"],
    ["mailmomy", "Mailmomy", "mailmomy.com"],
    ["chammy-info", "Mailinator (chammy.info)", "mailinator.com"],
    ["thisisnotmyrealemail-com", "Mailinator (thisisnotmyrealemail.com)", "mailinator.com"],
    ["notmailinator-com", "Mailinator (notmailinator.com)", "mailinator.com"],
    ["spamhereplease-com", "Mailinator (spamhereplease.com)", "mailinator.com"],
    ["sendspamhere-com", "Mailinator (sendspamhere.com)", "mailinator.com"],
    ["sendfree-org", "Mailinator (sendfree.org)", "mailinator.com"],
    ["junk-beats-org", "Mailinator (junk.beats.org)", "mailinator.com"],
    ["junk-ihmehl-com", "Mailinator (junk.ihmehl.com)", "mailinator.com"],
    ["junk-noplay-org", "Mailinator (junk.noplay.org)", "mailinator.com"],
    ["junk-vanillasystem-com", "Mailinator (junk.vanillasystem.com)", "mailinator.com"],
    ["spam-jasonpearce-com", "Mailinator (spam.jasonpearce.com)", "mailinator.com"],
    ["fish-skytale-net", "Mailinator (fish.skytale.net)", "mailinator.com"],
    ["spam-mccrew-com", "Mailinator (spam.mccrew.com)", "mailinator.com"],
    ["dropmail-click", "DropMail.click", "dropmail.click"],
    ["spam-coroiu-com", "Mailinator (spam.coroiu.com)", "mailinator.com"],
    ["spam-deluser-net", "Mailinator (spam.deluser.net)", "mailinator.com"],
    ["spam-dhsf-net", "Mailinator (spam.dhsf.net)", "mailinator.com"],
    ["spam-lucatnt-com", "Mailinator (spam.lucatnt.com)", "mailinator.com"],
    ["spam-lyceum-life-com-ru", "Mailinator (spam.lyceum-life.com.ru)", "mailinator.com"],
    ["spam-netpirates-net", "Mailinator (spam.netpirates.net)", "mailinator.com"],
    ["spam-no-ip-net", "Mailinator (spam.no-ip.net)", "mailinator.com"],
    ["spam-ozh-org", "Mailinator (spam.ozh.org)", "mailinator.com"],
    ["spam-pyphus-org", "Mailinator (spam.pyphus.org)", "mailinator.com"],
    ["spam-shep-pw", "Mailinator (spam.shep.pw)", "mailinator.com"],
    ["spam-wtf-at", "Mailinator (spam.wtf.at)", "mailinator.com"],
    ["spam-wulczer-org", "Mailinator (spam.wulczer.org)", "mailinator.com"],
    ["crap-kakadua-net", "Mailinator (crap.kakadua.net)", "mailinator.com"],
    ["spam-janlugt-nl", "Mailinator (spam.janlugt.nl)", "mailinator.com"],
    ["min-burningfish-net", "Mailinator (min.burningfish.net)", "mailinator.com"],
    ["sink-fblay-com", "Mailinator (sink.fblay.com)", "mailinator.com"],
    ["tempgmailer", "TempGmailer", "tempgmailer.com"],
    ["temp-mail-org", "Temp-Mail.org", "temp-mail.org"],
    ["xkx-me", "XKX.me", "xkx.me"],
    ["gonebox-email", "Gonebox Email", "gonebox.email"],
    ["mailcat-ai", "Mailcat AI", "mailcat.ai"],
    ["tempgo-email", "TempGo Email", "tempgo.email"],
    ["restmail-net", "Restmail.net", "restmail.net"],
    ["dropmail-me", "DropMail.me", "dropmail.me"],
    ["ten-minute-mail-net", "10MinuteMail.net", "10minutemail.net"],
  ].freeze
end
