import type { Channel } from "./types";

/**
 * 后端分组映射
 * 共享同一后端 API 的渠道归入同一组，组内一个渠道失败时可跳过其余渠道
 */
export const backendGroups: Record<string, Channel[]> = {
  mailinator: [
    "mailinator",
    "sogetthis-com",
    "bobmail-info",
    "suremail-info",
    "binkmail-com",
    "veryrealemail-com",
    "chammy-info",
    "thisisnotmyrealemail-com",
    "notmailinator-com",
    "spamhereplease-com",
    "sendspamhere-com",
    "sendfree-org",
    "junk-beats-org",
    "junk-ihmehl-com",
    "junk-noplay-org",
    "junk-vanillasystem-com",
    "spam-jasonpearce-com",
    "fish-skytale-net",
    "spam-mccrew-com",
    "spam-coroiu-com",
    "crap-kakadua-net",
    "spam-janlugt-nl",
    "min-burningfish-net",
    "sink-fblay-com",
    "spam-deluser-net",
    "spam-dhsf-net",
    "spam-lucatnt-com",
    "spam-lyceum-life-com-ru",
    "spam-netpirates-net",
    "spam-no-ip-net",
    "spam-ozh-org",
    "spam-pyphus-org",
    "spam-shep-pw",
    "spam-wtf-at",
    "spam-wulczer-org",
    "sp-woot-at",
    "blackhole-djurby-se",
    "block-bdea-cc",
    "b-smelly-cc",
    "carlton183-changeip-net",
    "dea-soon-it",
    "disposable-al-sudani-com",
    "disposable-nogonad-nl",
    "ebs-com-ar",
    "etgdev-de",
    "fwd2m-eszett-es",
    "j-fairuse-org",
    "jama-trenet-eu",
    "m-887-at",
    "m8r-davidfuhr-de",
    "m8r-mcasal-com",
    "mail-bentrask-com",
    "mail-fsmash-org",
    "mailinatorzz-mooo-com",
    "mi-meon-be",
    "mn-curppa-com",
    "m-nik-me",
    "mtmdev-com",
    "nospam-thurstons-us",
    "notfond-404-mn",
    "null-k3vin-net",
    "ramjane-mooo-com",
    "rauxa-seny-cat",
    "really-istrash-com",
    "spam-hortuk-ovh",
    "test-unergie-com",
    "torch-yi-org",
    "t-zibet-net",
  ],
  mailmomy: [
    "mailmomy",
    "16888888-cyou",
    "17666688-shop",
    "282mail-com",
    "bsdu32-buzz",
    "doxu243-buzz",
    "easyme-pro",
    "evergreenco-shop",
    "layueming-pics",
    "mingyuekeji-online",
    "mingyueming-click",
    "mingyueming-shop",
    "mingyukeji-lol",
    "nuxh62-space",
    "proid-cloud-ip-cc",
    "sbook-pics",
    "xue32-buzz",
  ],
  getnada: [
    "getnada",
    "1vpn-net",
    "abematv-com",
    "abematv-net",
    "abematv-org",
    "aceh-cc",
    "bangkabelitung-net",
    "cctruyen-com",
    "getnada-com",
    "getnada-email",
    "getnada-net",
    "jawatengah-net",
    "jawatimur-net",
    "kalimantanbarat-net",
    "kalimantanselatan-net",
    "kalimantantengah-net",
    "kalimantantimur-net",
    "kalimantanutara-net",
    "kepulauanriau-net",
    "luxury345-com",
    "malukuutara-net",
    "nusatenggarabarat-net",
    "nusatenggaratimur-net",
    "papuabarat-net",
    "papuabaratdaya-net",
    "papuaselatan-net",
    "pehol-com",
    "ptruyen-com",
    "pulaubali-net",
    "sulawesibarat-net",
    "sulawesiselatan-net",
    "sulawesitengah-net",
    "sulawesitenggara-net",
    "sumaterabarat-net",
    "sumateraselatan-net",
    "sumaterautara-net",
    "villatogel-com",
    "web-library-net",
  ],
  guerrillamail: [
    "guerrillamail",
    "sharklasers",
    "sharklasers-com",
    "grr-la",
    "grr-la-com",
    "guerrillamail-info",
    "spam4me",
    "guerrillamail-net",
    "guerrillamail-org",
    "guerrillamailblock",
    "guerrillamail-com",
    "guerrillamail-com-www",
  ],
  moakt: [
    "moakt",
    "drmail-in",
    "teml-net",
    "tmpeml-com",
    "tmpbox-net",
    "moakt-cc",
    "disbox-net",
    "tmpmail-org",
    "tmpmail-net",
    "tmails-net",
    "disbox-org",
    "moakt-co",
    "moakt-ws",
    "tmail-ws",
    "bareed-ws",
  ],
  "catchmail": [
    "catchmail",
    "catchmail-mailistry",
    "catchmail-zeppost",
  ],
  "mailforspam": [
    "mailforspam",
    "mailforspam-tempmail-io",
    "mailforspam-disposable",
  ],
  "10minute-one": [
    "10minute-one",
    "xghff-com",
    "oqqaj-com",
    "psovv-com",
    "dbwot-com",
    "ygwpr-com",
    "imxwe-com",
  ],
  "tempmail-plus": [
    "tempmail-plus",
    "fexpost-com",
    "fexbox-org",
    "mailbox-in-ua",
    "rover-info",
    "chitthi-in",
    "fextemp-com",
    "any-pink",
    "merepost-com",
  ],
  "zhujump": [
    "jqkjqk-xyz",
    "lyhlevi-com",
  ],
  "mail-cx": [
    "mail-cx",
    "ddker-com",
  ],
  "fake-legal": [
    "fake-legal",
    "imgui-de",
    "pulsewebmenu-de",
  ],
  "socketio-mail": [
    "mjj-cm",
    "linshi-co",
  ],
  "neighbours": [
    "neighbours-sh",
    "neighbours",
  ],
  "mail-tm": [
    "mail-tm",
  ],
  "one-sec-mail": [
    "1sec-mail",
  ],
  "vip-215": [
    "vip-215",
  ],
};

/**
 * 渠道 → 后端组名的反向映射（运行时构建）
 */
export const channelToBackend: Map<Channel, string> = new Map();

for (const [backend, channels] of Object.entries(backendGroups)) {
  for (const ch of channels) {
    channelToBackend.set(ch, backend);
  }
}
